### PR TITLE
Run ot-recorder as a non-privileged user.

### LINKED ISSUE #32: ot-recorder should not run as root
We should avoid running binaries as root inside docker containers whenever possible. ot-recorder runs as root by default, but it's possible to run it as another user without changes to the Dockerfile. Maybe an update to the documentation to reflect the instructions above could be helpful for some people out there.

To run as another user, first create a user on the host just for `ot-recorder`. Resist the temptation of using the existing `nobody` user. Let's suppose we're using user `recorder` and group `recorder`, both with the same uid/gid (10000). The examples below work on a Debian system, but should be similar to most other distros:

```
export user=recorder
export uid=10000
sudo groupadd -g $uid $user
sudo useradd -c "$user" -d "/nonexistent" -g "$user" --uid $uid -s "/usr/sbin/nologin" $user
```

Now, create a directory to hold your static data. AFAICT, we can't use docker volumes (without altering the Dockerfile) as docker always mounts those as root:

```
mkdir /path/to/store/recorder/data
chown recorder:recorder /path/to/store/recorder/data
```

When running the container with `docker run`, replace the `-v docker_store:/store` option with `-v /path/to/store/recorder/data:/store` and add `-u 10000:10000`. Note that we need to use the UID/GID of the just user "recorder" on the host. We can't just use the string "recorder" here since this user is not available inside the docker container.

This works, but proper support for non-root users by default inside the Dockerfile would be a better solution.

### PR DESCRIPTION
**Pull request by marcopaganini**
Closes #32

### CODE REVIEW

**Comment by jpmens** [comment]
@marcopaganini thank you for this. It looks good to me, but I have a question.

In `entrypoint.sh` you check to see whether we're running as root and "fix" the ownership of the mount point respectively all Recorder files in store, etc. Will this break anything for existing users who upgrade into this container version?

**Comment by marcopaganini** [comment]
We can test but I think it will work fine. Note that entrypoint still runs
as root (the first time it's called). At the point, it will change the
ownership of the mount point recursively to be that of the "internal" user.
For existing users (which have everything set as root in the mountpoint),
those files will end up owned as the internal user. If for any reason they
move back to the old version, root can still access them.

**Comment by jpmens** [comment]
Merged, thank you.

**Comment by jpmens** [comment]
Pushed to docker hub as `owntracks/recorder:0.8.6-10`

**Pull request merged**
